// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moamgblbasjcbxulwstr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYW1nYmxiYXNqY2J4dWx3c3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDY1NzksImV4cCI6MjA2ODc4MjU3OX0.PS9vor3Si_3AY0nYVkTXV2tds6evQBWx2K9ewmH6SBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});